# Generated by Django 3.0.1 on 2020-02-21 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuType', models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg')], default=None, max_length=191)),
                ('menu_image', models.ImageField(upload_to='menuType')),
                ('menu', models.CharField(max_length=191, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191)),
                ('email', models.CharField(max_length=191)),
                ('contact_no', models.CharField(max_length=191)),
                ('age', models.CharField(max_length=191)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cuisines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuType', models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg')], default=None, max_length=191)),
                ('dish_image', models.ImageField(upload_to='dish')),
                ('dish_name', models.CharField(max_length=191)),
                ('cost', models.IntegerField(default=0)),
                ('dish_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuType', models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg')], default=None, max_length=191)),
                ('dish_name', models.CharField(max_length=191)),
                ('unit_price', models.IntegerField(default=0)),
                ('cost', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=1)),
                ('username', models.CharField(max_length=191)),
                ('contact_no', models.CharField(default=0, max_length=191)),
                ('table_no', models.IntegerField(default=0)),
                ('dish_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Menu')),
            ],
        ),
    ]
